# Generated by Django 4.2.7 on 2023-11-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.URLField()),
                ('short_link', models.CharField(max_length=6)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
    ]
