# Generated by Django 4.2.7 on 2023-11-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpair',
            name='short_link',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
