# Generated by Django 4.2.7 on 2023-11-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_linkpair_short_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkpair',
            options={'ordering': ['-pk']},
        ),
    ]
