# Generated by Django 4.2.7 on 2023-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_alter_linkpair_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkpair',
            old_name='long_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='linkpair',
            name='short_link',
        ),
        migrations.AddField(
            model_name='linkpair',
            name='alias',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
