# Generated by Django 4.2.7 on 2023-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_rename_long_link_linkpair_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpair',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkpair',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkpair',
            name='alias',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
