# Generated by Django 4.2.7 on 2023-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_linkpair_is_active_linkpair_request_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpair',
            name='is_secured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkpair',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
