# Generated by Django 4.2.7 on 2023-11-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_linkpair_is_secured_linkpair_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer_url', models.URLField(null=True)),
                ('link_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referers', to='urlshortener.linkpair')),
            ],
        ),
    ]
