# Generated by Django 4.2.7 on 2023-11-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0007_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referer',
            name='trigger_dt',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-15 21:52:24.193574'),
            preserve_default=False,
        ),
    ]
